# Publish the state of each joint in /joint_states topic-----------------------------------
scara_joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

# Specifies how to control each individual joint -----------------------------------
arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - base_link__link_01
    - link_01__link_02
    - link_02__link_03
    - link_03__link_04

hand_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - link_04__link_05
    - link_04__link_06